apiVersion: apps/v1
kind: Deployment
metadata:
  name: sri-backend
spec:
  template:
    spec:
      serviceAccountName: sri-facturacion-sa
      containers:
        - name: sri-backend
          envFrom:
            - configMapRef:
                name: sri-facturacion-config
            - secretRef:
                name: sri-facturacion-secrets
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: sri-facturacion-aws-secrets
