apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sri-facturacion-aws-secrets
  labels:
    app: sri-facturacion-service
spec:
  provider: aws
  parameters:
    region: "us-east-1"
    objects: |
      - objectName: "/sri-facturacion/SUPABASE_KEY"
        objectType: "ssmparameter"
        objectAlias: "SUPABASE_KEY"
      - objectName: "/sri-facturacion/JWT_SECRET"
        objectType: "ssmparameter"
        objectAlias: "JWT_SECRET"
      - objectName: "/sri-facturacion/FLASK_SECRET_KEY"
        objectType: "ssmparameter"
        objectAlias: "FLASK_SECRET_KEY"
  secretObjects:
    - secretName: sri-facturacion-secrets
      type: Opaque
      data:
        - objectName: SUPABASE_KEY
          key: SUPABASE_KEY
        - objectName: JWT_SECRET
          key: JWT_SECRET
        - objectName: FLASK_SECRET_KEY
          key: FLASK_SECRET_KEY
