apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: sri-facturacion-local

namespace: sri-facturacion

resources:
  - ../../bases

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: sri-facturacion-config
  - path: backend-patch.yaml
    target:
      kind: Deployment
      name: sri-backend
  - path: frontend-patch.yaml
    target:
      kind: Deployment
      name: sri-frontend
  - patch: |-
      - op: replace
        path: /spec/ports
        value:
          - name: http
            port: 8088
            targetPort: 8080
            protocol: TCP
      - op: replace
        path: /spec/type
        value: LoadBalancer
    target:
      kind: Service
      name: sri-frontend-svc
  - patch: |-
      - op: replace
        path: /spec/ports
        value:
          - name: api
            port: 5000
            targetPort: 5000
            protocol: TCP
      - op: replace
        path: /spec/type
        value: LoadBalancer
    target:
      kind: Service
      name: sri-backend-svc

images:
  - name: sri-backend
    newName: sri-backend
    newTag: v1.2.0
  - name: sri-frontend
    newName: sri-frontend
    newTag: v1.2.0
