apiVersion: v1
kind: Service
metadata:
  name: sri-frontend-svc
  labels:
    app: sri-frontend
spec:
  type: ClusterIP
  selector:
    app: sri-frontend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
