apiVersion: apps/v1
kind: Deployment
metadata:
  name: sri-frontend
  labels:
    app: sri-frontend
    component: ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sri-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: sri-frontend
        component: ui
    spec:
      containers:
        - name: sri-frontend
          image: sri-frontend:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: sri-facturacion-config
                  key: BACKEND_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
