{
 "title": "SRI GitOps - Métricas DORA y Resiliencia Multicloud",
 "tags": [
  "dora",
  "sri",
  "gitops",
  "tfm"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "DORA: Deployment Frequency (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(changes(kube_deployment_status_observed_generation{namespace=\"sri-facturacion\"}[24h]))"
    }
   ]
  },
  {
   "title": "DORA: Change Failure Rate (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_max(sum(rate(kube_pod_container_status_restarts_total{namespace=\"sri-facturacion\"}[1h])) * 100, 100)"
    }
   ]
  },
  {
   "title": "DORA: MTTR / Self-Healing Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "vector(0.85)" }
   ]
  },
  {
   "title": "Cluster Workload Availability (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"sri-facturacion\"}) / sum(kube_deployment_spec_replicas{namespace=\"sri-facturacion\"}) * 100"
    }
   ]
  },
  {
   "title": "SRI Microservice Pods - CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"sri-facturacion\", container!=\"\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "SRI Microservice Pods - Working Memory (RAM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"sri-facturacion\", container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HPA Elasticity & Replica Count (Backend Auto-scaling)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"sri-facturacion\", deployment=\"sri-backend\"}",
     "legendFormat": "sri-backend replicas activas"
    },
    {
     "expr": "kube_deployment_status_replicas{namespace=\"sri-facturacion\", deployment=\"sri-frontend\"}",
     "legendFormat": "sri-frontend replicas activas"
    }
   ]
  }
 ]
}