apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sri-facturacion-local
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    cloud: local-docker-desktop
spec:
  project: default
  source:
    repoURL: https://github.com/JuanCrashe/sri-gitops-microservicio.git
    targetRevision: main
    path: gitops/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: sri-facturacion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
